// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (category_name, category_type, description)
VALUES ($1, $2, $3)
RETURNING id, category_name, category_type, description
`

type CreateCategoryParams struct {
	CategoryName string
	CategoryType string
	Description  string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.CategoryName, arg.CategoryType, arg.Description)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CategoryName,
		&i.CategoryType,
		&i.Description,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, category_name, category_type, description
FROM categories
ORDER BY id
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.CategoryName,
			&i.CategoryType,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, category_name, category_type, description
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CategoryName,
		&i.CategoryType,
		&i.Description,
	)
	return i, err
}

const getMainCategories = `-- name: GetMainCategories :many
SELECT id, category_name, description
FROM categories
WHERE category_type = 'main'
ORDER BY id
`

type GetMainCategoriesRow struct {
	ID           int32
	CategoryName string
	Description  string
}

func (q *Queries) GetMainCategories(ctx context.Context) ([]GetMainCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMainCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMainCategoriesRow
	for rows.Next() {
		var i GetMainCategoriesRow
		if err := rows.Scan(&i.ID, &i.CategoryName, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubCategories = `-- name: GetSubCategories :many
SELECT id, category_name, description
FROM categories
WHERE category_type = 'sub'
ORDER BY id
`

type GetSubCategoriesRow struct {
	ID           int32
	CategoryName string
	Description  string
}

func (q *Queries) GetSubCategories(ctx context.Context) ([]GetSubCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubCategoriesRow
	for rows.Next() {
		var i GetSubCategoriesRow
		if err := rows.Scan(&i.ID, &i.CategoryName, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET category_name = $2,
    category_type = $3,
    description = $4
WHERE id = $1
RETURNING id, category_name, category_type, description
`

type UpdateCategoryParams struct {
	ID           int32
	CategoryName string
	CategoryType string
	Description  string
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.CategoryName,
		arg.CategoryType,
		arg.Description,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CategoryName,
		&i.CategoryType,
		&i.Description,
	)
	return i, err
}
