// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaves.sql

package sqlc

import (
	"context"
	"time"
)

const createLeave = `-- name: CreateLeave :one
INSERT INTO leaves (user_id, start_date, end_date, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, start_date, end_date, reason, created_at, updated_at
`

type CreateLeaveParams struct {
	UserID    int32
	StartDate time.Time
	EndDate   time.Time
	Reason    string
}

func (q *Queries) CreateLeave(ctx context.Context, arg CreateLeaveParams) (Leafe, error) {
	row := q.db.QueryRowContext(ctx, createLeave,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.Reason,
	)
	var i Leafe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLeave = `-- name: DeleteLeave :exec
DELETE FROM leaves
WHERE id = $1
`

func (q *Queries) DeleteLeave(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteLeave, id)
	return err
}

const getAllLeaves = `-- name: GetAllLeaves :many
SELECT id, user_id, start_date, end_date, reason, created_at, updated_at
FROM leaves
ORDER BY start_date DESC
`

func (q *Queries) GetAllLeaves(ctx context.Context) ([]Leafe, error) {
	rows, err := q.db.QueryContext(ctx, getAllLeaves)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Leafe
	for rows.Next() {
		var i Leafe
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaveByID = `-- name: GetLeaveByID :one
SELECT id, user_id, start_date, end_date, reason, created_at, updated_at
FROM leaves
WHERE id = $1
`

func (q *Queries) GetLeaveByID(ctx context.Context, id int32) (Leafe, error) {
	row := q.db.QueryRowContext(ctx, getLeaveByID, id)
	var i Leafe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeavesByUser = `-- name: GetLeavesByUser :many
SELECT id, user_id, start_date, end_date, reason, created_at, updated_at
FROM leaves
WHERE user_id = $1
ORDER BY start_date DESC
`

func (q *Queries) GetLeavesByUser(ctx context.Context, userID int32) ([]Leafe, error) {
	rows, err := q.db.QueryContext(ctx, getLeavesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Leafe
	for rows.Next() {
		var i Leafe
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLeave = `-- name: UpdateLeave :one
UPDATE leaves
SET start_date = $2,
    end_date = $3,
    reason = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, start_date, end_date, reason, created_at, updated_at
`

type UpdateLeaveParams struct {
	ID        int32
	StartDate time.Time
	EndDate   time.Time
	Reason    string
}

func (q *Queries) UpdateLeave(ctx context.Context, arg UpdateLeaveParams) (Leafe, error) {
	row := q.db.QueryRowContext(ctx, updateLeave,
		arg.ID,
		arg.StartDate,
		arg.EndDate,
		arg.Reason,
	)
	var i Leafe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
