// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: missiond_participants.sql

package sqlc

import (
	"context"
)

const addMissionParticipant = `-- name: AddMissionParticipant :exec
INSERT INTO mission_participants (mission_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (mission_id, user_id) DO NOTHING
`

type AddMissionParticipantParams struct {
	MissionID int32
	UserID    int32
	Role      string
}

func (q *Queries) AddMissionParticipant(ctx context.Context, arg AddMissionParticipantParams) error {
	_, err := q.db.ExecContext(ctx, addMissionParticipant, arg.MissionID, arg.UserID, arg.Role)
	return err
}

const deleteParticipantsByMission = `-- name: DeleteParticipantsByMission :exec
DELETE FROM mission_participants WHERE mission_id = $1
`

func (q *Queries) DeleteParticipantsByMission(ctx context.Context, missionID int32) error {
	_, err := q.db.ExecContext(ctx, deleteParticipantsByMission, missionID)
	return err
}

const getMissionParticipants = `-- name: GetMissionParticipants :many
SELECT 
  u.id,
  u.name,
  mp.role
FROM mission_participants mp
JOIN users u ON mp.user_id = u.id
WHERE mp.mission_id = $1
ORDER BY u.name
`

type GetMissionParticipantsRow struct {
	ID   int32
	Name string
	Role string
}

func (q *Queries) GetMissionParticipants(ctx context.Context, missionID int32) ([]GetMissionParticipantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMissionParticipants, missionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMissionParticipantsRow
	for rows.Next() {
		var i GetMissionParticipantsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMissionParticipant = `-- name: RemoveMissionParticipant :exec
DELETE FROM mission_participants
WHERE mission_id = $1 AND user_id = $2
`

type RemoveMissionParticipantParams struct {
	MissionID int32
	UserID    int32
}

func (q *Queries) RemoveMissionParticipant(ctx context.Context, arg RemoveMissionParticipantParams) error {
	_, err := q.db.ExecContext(ctx, removeMissionParticipant, arg.MissionID, arg.UserID)
	return err
}

const updateMissionParticipant = `-- name: UpdateMissionParticipant :exec
UPDATE mission_participants
SET role = $3
WHERE mission_id = $1 AND user_id = $2
`

type UpdateMissionParticipantParams struct {
	MissionID int32
	UserID    int32
	Role      string
}

func (q *Queries) UpdateMissionParticipant(ctx context.Context, arg UpdateMissionParticipantParams) error {
	_, err := q.db.ExecContext(ctx, updateMissionParticipant, arg.MissionID, arg.UserID, arg.Role)
	return err
}
