// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mission.sql

package sqlc

import (
	"context"
	"time"
)

const createMission = `-- name: CreateMission :one
INSERT INTO missions (
  mission_name,
  coordinator_num,
  main_category,
  sub_category,
  month,
  created_by
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, mission_name, coordinator_num, main_category, sub_category, month, created_by, created_at
`

type CreateMissionParams struct {
	MissionName    string
	CoordinatorNum int32
	MainCategory   int32
	SubCategory    int32
	Month          int32
	CreatedBy      int32
}

func (q *Queries) CreateMission(ctx context.Context, arg CreateMissionParams) (Mission, error) {
	row := q.db.QueryRowContext(ctx, createMission,
		arg.MissionName,
		arg.CoordinatorNum,
		arg.MainCategory,
		arg.SubCategory,
		arg.Month,
		arg.CreatedBy,
	)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.MissionName,
		&i.CoordinatorNum,
		&i.MainCategory,
		&i.SubCategory,
		&i.Month,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMission = `-- name: DeleteMission :exec
DELETE FROM missions WHERE id = $1
`

func (q *Queries) DeleteMission(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMission, id)
	return err
}

const getAllMissions = `-- name: GetAllMissions :many
SELECT 
  m.id,
  m.mission_name,
  m.coordinator_num,
  m.main_category,
  m.sub_category,
  m.month,
  m.created_by,
  u.name AS created_by_name,
  m.created_at
FROM missions m
JOIN users u ON m.created_by = u.id
ORDER BY m.id DESC
`

type GetAllMissionsRow struct {
	ID             int32
	MissionName    string
	CoordinatorNum int32
	MainCategory   int32
	SubCategory    int32
	Month          int32
	CreatedBy      int32
	CreatedByName  string
	CreatedAt      time.Time
}

func (q *Queries) GetAllMissions(ctx context.Context) ([]GetAllMissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllMissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMissionsRow
	for rows.Next() {
		var i GetAllMissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.MissionName,
			&i.CoordinatorNum,
			&i.MainCategory,
			&i.SubCategory,
			&i.Month,
			&i.CreatedBy,
			&i.CreatedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMissionByID = `-- name: GetMissionByID :one
SELECT 
  m.id,
  m.mission_name,
  m.coordinator_num,
  m.main_category,
  m.sub_category,
  m.month,
  m.created_by,
  u.name AS created_by_name,
  m.created_at
FROM missions m
JOIN users u ON m.created_by = u.id
WHERE m.id = $1
`

type GetMissionByIDRow struct {
	ID             int32
	MissionName    string
	CoordinatorNum int32
	MainCategory   int32
	SubCategory    int32
	Month          int32
	CreatedBy      int32
	CreatedByName  string
	CreatedAt      time.Time
}

func (q *Queries) GetMissionByID(ctx context.Context, id int32) (GetMissionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMissionByID, id)
	var i GetMissionByIDRow
	err := row.Scan(
		&i.ID,
		&i.MissionName,
		&i.CoordinatorNum,
		&i.MainCategory,
		&i.SubCategory,
		&i.Month,
		&i.CreatedBy,
		&i.CreatedByName,
		&i.CreatedAt,
	)
	return i, err
}

const updateMission = `-- name: UpdateMission :one
UPDATE missions
SET
  mission_name = $1,
  coordinator_num = $2,
  main_category = $3,
  sub_category = $4,
  month = $5
WHERE id = $6
RETURNING id, mission_name, coordinator_num, main_category, sub_category, month, created_by, created_at
`

type UpdateMissionParams struct {
	MissionName    string
	CoordinatorNum int32
	MainCategory   int32
	SubCategory    int32
	Month          int32
	ID             int32
}

func (q *Queries) UpdateMission(ctx context.Context, arg UpdateMissionParams) (Mission, error) {
	row := q.db.QueryRowContext(ctx, updateMission,
		arg.MissionName,
		arg.CoordinatorNum,
		arg.MainCategory,
		arg.SubCategory,
		arg.Month,
		arg.ID,
	)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.MissionName,
		&i.CoordinatorNum,
		&i.MainCategory,
		&i.SubCategory,
		&i.Month,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
