// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Category struct {
	ID           int32
	CategoryName string
	CategoryType string
	Description  string
}

type Leafe struct {
	ID        int32
	UserID    int32
	StartDate time.Time
	EndDate   time.Time
	Reason    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Mission struct {
	ID             int32
	MissionName    string
	CoordinatorNum int32
	MainCategory   int32
	SubCategory    int32
	Day            int32
	Month          int32
	Year           int32
	DurationDays   int32
	CreatedBy      int32
	CreatedAt      time.Time
}

type MissionParticipant struct {
	MissionID int32
	UserID    int32
	Role      string
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Mobile    string
	Password  string
	Balance   int32
	Role      string
	CreatedAt time.Time
}
