// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type MainCategory struct {
	ID           int32
	CategoryName string
	Description  sql.NullString
}

type Mission struct {
	ID           int32
	MissionName  string
	PhgId1       int32
	PhgId2       int32
	PhgId3       int32
	PhgId4       int32
	PhgId5       int32
	MainCategory int32
	SubCategory  int32
	Month        int32
	Year         int32
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	NumberOfPhs  int32
	NumberOfVids int32
	Description  sql.NullString
	CreatedBy    int32
	Status       int32
}

type Phg struct {
	ID             int32
	Name           string
	Mobile         string
	MissionsCredit int32
	StartVacation  string
	EndVacation    string
	Status         string
	Note           sql.NullString
}

type SubCategory struct {
	ID           int32
	CategoryName string
	Description  sql.NullString
}

type User struct {
	ID        int32
	Name      string
	Username  string
	Email     string
	Mobile    string
	Password  string
	CreatedAt sql.NullTime
}
