// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"
)

const addUser = `-- name: AddUser :exec
INSERT INTO users (name, email, mobile, password) VALUES ($1, $2, $3, $4)
RETURNING id, name, username, email, mobile, password, created_at
`

type AddUserParams struct {
	Name     string
	Email    string
	Mobile   string
	Password string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.ExecContext(ctx, addUser,
		arg.Name,
		arg.Email,
		arg.Mobile,
		arg.Password,
	)
	return err
}

const checkUserByUsername = `-- name: CheckUserByUsername :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) CheckUserByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :exec
SELECT id, name, username, email, mobile, password, created_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, getAllUsers)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, username, email, mobile, password, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Mobile,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, name, username, email, mobile, password, created_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Mobile,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET name = $1, email = $2, mobile = $3, password = $4 WHERE id = $5
RETURNING id, name, username, email, mobile, password, created_at
`

type UpdateUserParams struct {
	Name     string
	Email    string
	Mobile   string
	Password string
	ID       int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Mobile,
		arg.Password,
		arg.ID,
	)
	return err
}
