// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addUser = `-- name: AddUser :one
INSERT INTO users (name, email, mobile, job, role, blocked, balance, negative_balance)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, email, mobile, job, password, blocked, balance, negative_balance, role, created_at
`

type AddUserParams struct {
	Name            string
	Email           string
	Mobile          string
	Job             string
	Role            string
	Blocked         bool
	Balance         int32
	NegativeBalance bool
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser,
		arg.Name,
		arg.Email,
		arg.Mobile,
		arg.Job,
		arg.Role,
		arg.Blocked,
		arg.Balance,
		arg.NegativeBalance,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Mobile,
		&i.Job,
		&i.Password,
		&i.Blocked,
		&i.Balance,
		&i.NegativeBalance,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const allowNegativeBalance = `-- name: AllowNegativeBalance :exec
UPDATE users
SET negative_balance = 'yes'
WHERE id = $1
`

func (q *Queries) AllowNegativeBalance(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, allowNegativeBalance, id)
	return err
}

const checkUserByEmail = `-- name: CheckUserByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) CheckUserByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUserByMobile = `-- name: CheckUserByMobile :one
SELECT EXISTS(SELECT 1 FROM users WHERE mobile = $1)
`

func (q *Queries) CheckUserByMobile(ctx context.Context, mobile string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserByMobile, mobile)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const disallowNegativeBalance = `-- name: DisallowNegativeBalance :exec
UPDATE users
SET negative_balance = 'no'
WHERE id = $1
`

func (q *Queries) DisallowNegativeBalance(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, disallowNegativeBalance, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, email, mobile, job, password, blocked, balance, negative_balance, role, created_at
FROM users
ORDER BY id
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Mobile,
			&i.Job,
			&i.Password,
			&i.Blocked,
			&i.Balance,
			&i.NegativeBalance,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, mobile, job, password, blocked, balance, negative_balance, role, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Mobile,
		&i.Job,
		&i.Password,
		&i.Blocked,
		&i.Balance,
		&i.NegativeBalance,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, mobile, job, password, blocked, balance, negative_balance, role, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Mobile,
		&i.Job,
		&i.Password,
		&i.Blocked,
		&i.Balance,
		&i.NegativeBalance,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByMobile = `-- name: GetUserByMobile :one
SELECT id, name, email, mobile, job, password, blocked, balance, negative_balance, role, created_at
FROM users
WHERE mobile = $1
`

func (q *Queries) GetUserByMobile(ctx context.Context, mobile string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByMobile, mobile)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Mobile,
		&i.Job,
		&i.Password,
		&i.Blocked,
		&i.Balance,
		&i.NegativeBalance,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserWithLeaves = `-- name: GetUserWithLeaves :many
SELECT 
    u.id as user_id,
    u.name,
    u.email,
    l.id as leave_id,
    l.start_date,
    l.end_date,
    l.reason,
    l.created_at as leave_created_at
FROM users u
LEFT JOIN leaves l ON u.id = l.user_id
WHERE u.id = $1
ORDER BY l.start_date DESC
`

type GetUserWithLeavesRow struct {
	UserID         int32
	Name           string
	Email          string
	LeaveID        sql.NullInt32
	StartDate      sql.NullTime
	EndDate        sql.NullTime
	Reason         sql.NullString
	LeaveCreatedAt sql.NullTime
}

func (q *Queries) GetUserWithLeaves(ctx context.Context, id int32) ([]GetUserWithLeavesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserWithLeaves, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWithLeavesRow
	for rows.Next() {
		var i GetUserWithLeavesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.LeaveID,
			&i.StartDate,
			&i.EndDate,
			&i.Reason,
			&i.LeaveCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithSufficientBalance = `-- name: GetUserWithSufficientBalance :many
SELECT id, name, email, mobile, job, password, blocked, balance, negative_balance, role, created_at
FROM users
WHERE balance >= $1
`

func (q *Queries) GetUserWithSufficientBalance(ctx context.Context, balance int32) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUserWithSufficientBalance, balance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Mobile,
			&i.Job,
			&i.Password,
			&i.Blocked,
			&i.Balance,
			&i.NegativeBalance,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const makeUserAdmin = `-- name: MakeUserAdmin :one
UPDATE users
SET role = 'admin'
WHERE id = $1
RETURNING id, name, email, mobile, job, password, blocked, balance, negative_balance, role, created_at
`

func (q *Queries) MakeUserAdmin(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, makeUserAdmin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Mobile,
		&i.Job,
		&i.Password,
		&i.Blocked,
		&i.Balance,
		&i.NegativeBalance,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const removeUserAdmin = `-- name: RemoveUserAdmin :one
UPDATE users
SET role = 'user'
WHERE id = $1
RETURNING id, name, email, mobile, job, password, blocked, balance, negative_balance, role, created_at
`

func (q *Queries) RemoveUserAdmin(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, removeUserAdmin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Mobile,
		&i.Job,
		&i.Password,
		&i.Blocked,
		&i.Balance,
		&i.NegativeBalance,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const updateBalance = `-- name: UpdateBalance :one
UPDATE users
SET balance = $1
WHERE id = $2
RETURNING id, name, email, mobile, job, password, blocked, balance, negative_balance, role, created_at
`

type UpdateBalanceParams struct {
	Balance int32
	ID      int32
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateBalance, arg.Balance, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Mobile,
		&i.Job,
		&i.Password,
		&i.Blocked,
		&i.Balance,
		&i.NegativeBalance,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users
SET password = $1
WHERE id = $2
RETURNING id, name, email, mobile, job, password, blocked, balance, negative_balance, role, created_at
`

type UpdatePasswordParams struct {
	Password string
	ID       int32
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updatePassword, arg.Password, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Mobile,
		&i.Job,
		&i.Password,
		&i.Blocked,
		&i.Balance,
		&i.NegativeBalance,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2,
    email = $3,
    mobile = $4,
    job = $5,   
    role = $6,
    blocked = $7
    
WHERE id = $1
RETURNING id, name, email, mobile, job, password, blocked, balance, negative_balance, role, created_at
`

type UpdateUserParams struct {
	ID      int32
	Name    string
	Email   string
	Mobile  string
	Job     string
	Role    string
	Blocked bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Mobile,
		arg.Job,
		arg.Role,
		arg.Blocked,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Mobile,
		&i.Job,
		&i.Password,
		&i.Blocked,
		&i.Balance,
		&i.NegativeBalance,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
